name: Windows Release

on:
  push:
    branches:
      - release  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Install deps
        run: bash ./.github/scripts/install-haxeflixel.sh

      - name: Build
        run: |
          lime build windows
          ls -lash ./export/neko/bin/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "release-windows"
          prerelease: true
          title: "Release Build Windows"
          files: |
            ./export/neko/bin/*
        id: "release_windows"
